(function () {
  const specs = [
    {
      id: "var-01-name",
      group: "Biến",
      title: "Biến 01 - Lưu chuỗi: userName",
      context: "Một app hồ sơ cần lưu tên người dùng để hiển thị ở màn hình chào mừng.",
      request: "Tạo biến userName có giá trị \"Zu\".",
      result: "Khi kiểm tra userName, kết quả là \"Zu\".",
      example: 'userName => "Zu"',
      hint: ["Tên là dữ liệu dạng chuỗi.", "Chuỗi cần đặt trong dấu nháy.", "Có thể dùng let hoặc const."],
      tests: [{ expression: "userName", expected: "Zu" }],
      solution: 'const userName = "Zu";',
    },
    {
      id: "var-02-age",
      group: "Biến",
      title: "Biến 02 - Tính tuổi: age",
      context: "Một form đăng ký biết năm sinh và cần tính tuổi hiện tại của người dùng.",
      request: "Tạo biến birthYear là 2000, currentYear là 2026 và age là tuổi tính từ hai biến đó.",
      result: "age bằng 26.",
      example: "age => 26",
      hint: ["Tuổi = năm hiện tại trừ năm sinh.", "Tạo biến trung gian trước, rồi tạo age từ hai biến đó."],
      tests: [
        { expression: "birthYear", expected: 2000 },
        { expression: "currentYear", expected: 2026 },
        { expression: "age", expected: 26 },
      ],
      solution: "const birthYear = 2000;\nconst currentYear = 2026;\nconst age = currentYear - birthYear;",
    },
    {
      id: "var-03-temperature",
      group: "Biến",
      title: "Biến 03 - Công thức: fahrenheit",
      context: "Một app thời tiết nhận nhiệt độ C và cần đổi sang độ F.",
      request: "Tạo biến celsius là 30 và fahrenheit theo công thức celsius * 9 / 5 + 32.",
      result: "fahrenheit bằng 86.",
      example: "fahrenheit => 86",
      hint: ["Đặt celsius trước.", "Sau đó dùng celsius để tính fahrenheit.", "Chú ý thứ tự phép nhân, chia và cộng."],
      tests: [
        { expression: "celsius", expected: 30 },
        { expression: "fahrenheit", expected: 86 },
      ],
      solution: "const celsius = 30;\nconst fahrenheit = celsius * 9 / 5 + 32;",
    },
    {
      id: "var-04-area",
      group: "Biến",
      title: "Biến 04 - Diện tích: area",
      context: "Một app xây dựng cần tính diện tích phòng hình chữ nhật.",
      request: "Tạo biến width là 6, height là 4 và area là diện tích hình chữ nhật.",
      result: "area bằng 24.",
      example: "area => 24",
      hint: ["Diện tích hình chữ nhật = chiều rộng nhân chiều cao.", "Phép nhân trong JavaScript dùng dấu *."],
      tests: [
        { expression: "width", expected: 6 },
        { expression: "height", expected: 4 },
        { expression: "area", expected: 24 },
      ],
      solution: "const width = 6;\nconst height = 4;\nconst area = width * height;",
    },
    {
      id: "var-05-perimeter",
      group: "Biến",
      title: "Biến 05 - Chu vi: perimeter",
      context: "Một thợ mộc cần tính chiều dài viền gỗ quanh một mặt bàn hình chữ nhật.",
      request: "Tạo biến length là 8, width là 3 và perimeter là chu vi hình chữ nhật.",
      result: "perimeter bằng 22.",
      example: "perimeter => 22",
      hint: ["Chu vi hình chữ nhật = (length + width) * 2.", "Dùng ngoặc tròn để cộng trước khi nhân."],
      tests: [
        { expression: "length", expected: 8 },
        { expression: "width", expected: 3 },
        { expression: "perimeter", expected: 22 },
      ],
      solution: "const length = 8;\nconst width = 3;\nconst perimeter = (length + width) * 2;",
    },
    {
      id: "var-06-total-price",
      group: "Biến",
      title: "Biến 06 - Tổng tiền: totalPrice",
      context: "Một giỏ hàng cần tính tổng tiền từ đơn giá và số lượng.",
      request: "Tạo biến price là 12000, quantity là 5 và totalPrice là tổng tiền.",
      result: "totalPrice bằng 60000.",
      example: "totalPrice => 60000",
      hint: ["Tổng tiền = giá một món nhân số lượng.", "Đặt tên biến đúng như đề bài để app kiểm tra được."],
      tests: [
        { expression: "price", expected: 12000 },
        { expression: "quantity", expected: 5 },
        { expression: "totalPrice", expected: 60000 },
      ],
      solution: "const price = 12000;\nconst quantity = 5;\nconst totalPrice = price * quantity;",
    },
    {
      id: "var-07-full-name",
      group: "Biến",
      title: "Biến 07 - Ghép chuỗi: fullName",
      context: "Một hồ sơ lưu riêng họ và tên, nhưng giao diện cần hiển thị đầy đủ.",
      request: "Tạo firstName là \"An\", lastName là \"Nguyen\" và fullName có một dấu cách ở giữa.",
      result: "fullName bằng \"An Nguyen\".",
      example: 'fullName => "An Nguyen"',
      hint: ["Dùng dấu + để nối chuỗi.", "Giữa firstName và lastName cần có chuỗi \" \"."],
      tests: [
        { expression: "firstName", expected: "An" },
        { expression: "lastName", expected: "Nguyen" },
        { expression: "fullName", expected: "An Nguyen" },
      ],
      solution: 'const firstName = "An";\nconst lastName = "Nguyen";\nconst fullName = firstName + " " + lastName;',
    },
    {
      id: "var-08-boolean",
      group: "Biến",
      title: "Biến 08 - Boolean: isLoggedIn",
      context: "Một website cần biết người dùng đã đăng nhập hay chưa để hiện nút phù hợp.",
      request: "Tạo biến isLoggedIn có giá trị true.",
      result: "isLoggedIn bằng true.",
      example: "isLoggedIn => true",
      hint: ["true là boolean, không phải chuỗi.", "Không đặt true trong dấu nháy."],
      tests: [{ expression: "isLoggedIn", expected: true }],
      solution: "const isLoggedIn = true;",
    },
    {
      id: "var-09-compare",
      group: "Biến",
      title: "Biến 09 - So sánh: passed",
      context: "Một lớp học cần biết điểm của học sinh đã qua mức đạt hay chưa.",
      request: "Tạo biến score là 85 và passed là kết quả kiểm tra score >= 50.",
      result: "passed bằng true.",
      example: "passed => true",
      hint: ["Toán tử >= trả về true hoặc false.", "passed nên được tạo từ biểu thức so sánh."],
      tests: [
        { expression: "score", expected: 85 },
        { expression: "passed", expected: true },
      ],
      solution: "const score = 85;\nconst passed = score >= 50;",
    },
    {
      id: "var-10-discount",
      group: "Biến",
      title: "Biến 10 - Giảm giá: finalPrice",
      context: "Một cửa hàng có giá gốc và số tiền giảm, cần tính giá cuối cùng.",
      request: "Tạo originalPrice là 100000, discount là 15000 và finalPrice là giá sau giảm.",
      result: "finalPrice bằng 85000.",
      example: "finalPrice => 85000",
      hint: ["Giá sau giảm = giá gốc trừ số tiền giảm.", "Dùng dấu - cho phép trừ."],
      tests: [
        { expression: "originalPrice", expected: 100000 },
        { expression: "discount", expected: 15000 },
        { expression: "finalPrice", expected: 85000 },
      ],
      solution: "const originalPrice = 100000;\nconst discount = 15000;\nconst finalPrice = originalPrice - discount;",
    },
    {
      id: "if-01-even",
      group: "If Else",
      title: "If Else 01 - Chẵn lẻ: isEven",
      context: "Một trò chơi chia người chơi theo số thứ tự chẵn hoặc lẻ.",
      request: "Tạo hàm isEven nhận n.",
      result: "Trả về true nếu n là số chẵn, ngược lại false.",
      example: "isEven(4) => true\nisEven(7) => false",
      hint: ["Số chẵn chia cho 2 dư 0.", "Dùng toán tử % để lấy phần dư.", "Có thể dùng if else hoặc trả về trực tiếp biểu thức so sánh."],
      tests: [
        { expression: "isEven(4)", expected: true },
        { expression: "isEven(7)", expected: false },
        { expression: "isEven(0)", expected: true },
      ],
      solution: "function isEven(n) {\n  return n % 2 === 0;\n}",
    },
    {
      id: "if-02-positive",
      group: "If Else",
      title: "If Else 02 - Số dương: isPositive",
      context: "Một báo cáo tài chính cần biết khoản thay đổi có đang dương hay không.",
      request: "Tạo hàm isPositive nhận n.",
      result: "Trả về true nếu n lớn hơn 0.",
      example: "isPositive(5) => true\nisPositive(-2) => false",
      hint: ["Số dương là số lớn hơn 0.", "Dùng toán tử > để so sánh."],
      tests: [
        { expression: "isPositive(5)", expected: true },
        { expression: "isPositive(-2)", expected: false },
        { expression: "isPositive(0)", expected: false },
      ],
      solution: "function isPositive(n) {\n  return n > 0;\n}",
    },
    {
      id: "if-03-compare-two",
      group: "If Else",
      title: "If Else 03 - So sánh 2 số: compareNumbers",
      context: "Một bảng xếp hạng cần mô tả quan hệ giữa hai điểm số.",
      request: "Tạo hàm compareNumbers nhận a và b.",
      result: "Trả về \"a lớn hơn\", \"b lớn hơn\" hoặc \"bằng nhau\".",
      example: 'compareNumbers(5, 3) => "a lớn hơn"\ncompareNumbers(2, 7) => "b lớn hơn"',
      hint: ["Cần xét ba trường hợp.", "Dùng if cho a > b, else if cho b > a, còn lại là bằng nhau."],
      tests: [
        { expression: "compareNumbers(5, 3)", expected: "a lớn hơn" },
        { expression: "compareNumbers(2, 7)", expected: "b lớn hơn" },
        { expression: "compareNumbers(4, 4)", expected: "bằng nhau" },
      ],
      solution: 'function compareNumbers(a, b) {\n  if (a > b) return "a lớn hơn";\n  if (b > a) return "b lớn hơn";\n  return "bằng nhau";\n}',
    },
    {
      id: "if-04-max-three",
      group: "If Else",
      title: "If Else 04 - Lớn nhất 3 số: maxOfThree",
      context: "Một hệ thống điểm cần lấy điểm cao nhất trong ba lần làm bài.",
      request: "Tạo hàm maxOfThree nhận a, b và c.",
      result: "Trả về số lớn nhất.",
      example: "maxOfThree(3, 9, 4) => 9",
      hint: ["Tạm coi a là lớn nhất.", "So sánh b với số lớn nhất hiện tại.", "So sánh tiếp c với số lớn nhất hiện tại."],
      tests: [
        { expression: "maxOfThree(3, 9, 4)", expected: 9 },
        { expression: "maxOfThree(10, 2, 8)", expected: 10 },
        { expression: "maxOfThree(1, 5, 7)", expected: 7 },
      ],
      solution: "function maxOfThree(a, b, c) {\n  let max = a;\n  if (b > max) max = b;\n  if (c > max) max = c;\n  return max;\n}",
    },
    {
      id: "if-05-grade",
      group: "If Else",
      title: "If Else 05 - Xếp loại điểm: getGrade",
      context: "Một lớp học cần đổi điểm số thành xếp loại chữ.",
      request: "Tạo hàm getGrade nhận score.",
      result: "Trả về A nếu >= 90, B nếu >= 80, C nếu >= 70, D nếu >= 60, còn lại F.",
      example: 'getGrade(95) => "A"\ngetGrade(72) => "C"',
      hint: ["Kiểm tra từ mốc cao xuống thấp.", "Nếu kiểm tra từ thấp lên, điểm 95 có thể bị bắt nhầm ở mốc 60."],
      tests: [
        { expression: "getGrade(95)", expected: "A" },
        { expression: "getGrade(85)", expected: "B" },
        { expression: "getGrade(72)", expected: "C" },
        { expression: "getGrade(61)", expected: "D" },
        { expression: "getGrade(40)", expected: "F" },
      ],
      solution: 'function getGrade(score) {\n  if (score >= 90) return "A";\n  if (score >= 80) return "B";\n  if (score >= 70) return "C";\n  if (score >= 60) return "D";\n  return "F";\n}',
    },
    {
      id: "if-06-login",
      group: "If Else",
      title: "If Else 06 - Đăng nhập: canLogin",
      context: "Một app chỉ cho đăng nhập khi tài khoản đang hoạt động và mật khẩu đúng.",
      request: "Tạo hàm canLogin nhận isActive và passwordCorrect.",
      result: "Trả về true khi cả hai điều kiện đều đúng.",
      example: "canLogin(true, true) => true\ncanLogin(true, false) => false",
      hint: ["Cần cả hai điều kiện đúng cùng lúc.", "Toán tử && nghĩa là và."],
      tests: [
        { expression: "canLogin(true, true)", expected: true },
        { expression: "canLogin(true, false)", expected: false },
        { expression: "canLogin(false, true)", expected: false },
      ],
      solution: "function canLogin(isActive, passwordCorrect) {\n  return isActive && passwordCorrect;\n}",
    },
    {
      id: "if-07-discount",
      group: "If Else",
      title: "If Else 07 - Giảm giá: getDiscount",
      context: "Một cửa hàng muốn giảm giá cho đơn hàng lớn.",
      request: "Tạo hàm getDiscount nhận total.",
      result: "Trả về 20 nếu total >= 1000000, 10 nếu total >= 500000, còn lại 0.",
      example: "getDiscount(1200000) => 20\ngetDiscount(300000) => 0",
      hint: ["Kiểm tra mốc lớn trước.", "Mỗi nhánh return phần trăm giảm giá."],
      tests: [
        { expression: "getDiscount(1200000)", expected: 20 },
        { expression: "getDiscount(700000)", expected: 10 },
        { expression: "getDiscount(300000)", expected: 0 },
      ],
      solution: "function getDiscount(total) {\n  if (total >= 1000000) return 20;\n  if (total >= 500000) return 10;\n  return 0;\n}",
    },
    {
      id: "if-08-shipping",
      group: "If Else",
      title: "If Else 08 - Phí ship: shippingFee",
      context: "Một shop miễn phí vận chuyển cho đơn hàng đủ lớn.",
      request: "Tạo hàm shippingFee nhận total.",
      result: "Trả về 0 nếu total >= 300000, ngược lại 30000.",
      example: "shippingFee(350000) => 0\nshippingFee(100000) => 30000",
      hint: ["Có hai trường hợp.", "Dùng if else hoặc toán tử ba ngôi đều được."],
      tests: [
        { expression: "shippingFee(350000)", expected: 0 },
        { expression: "shippingFee(300000)", expected: 0 },
        { expression: "shippingFee(100000)", expected: 30000 },
      ],
      solution: "function shippingFee(total) {\n  if (total >= 300000) return 0;\n  return 30000;\n}",
    },
    {
      id: "if-09-ticket",
      group: "If Else",
      title: "If Else 09 - Giá vé theo tuổi: ticketPrice",
      context: "Một rạp phim tính giá vé khác nhau theo độ tuổi.",
      request: "Tạo hàm ticketPrice nhận age.",
      result: "Trả về 0 nếu dưới 6 tuổi, 50000 nếu dưới 18 tuổi, còn lại 90000.",
      example: "ticketPrice(5) => 0\nticketPrice(15) => 50000",
      hint: ["Kiểm tra nhóm tuổi nhỏ trước.", "Sau khi return, hàm dừng nên không cần else cũng được."],
      tests: [
        { expression: "ticketPrice(5)", expected: 0 },
        { expression: "ticketPrice(15)", expected: 50000 },
        { expression: "ticketPrice(25)", expected: 90000 },
      ],
      solution: "function ticketPrice(age) {\n  if (age < 6) return 0;\n  if (age < 18) return 50000;\n  return 90000;\n}",
    },
    {
      id: "if-10-password",
      group: "If Else",
      title: "If Else 10 - Độ dài mật khẩu: isStrongPassword",
      context: "Một form đăng ký muốn chặn mật khẩu quá ngắn.",
      request: "Tạo hàm isStrongPassword nhận password.",
      result: "Trả về true nếu password có ít nhất 8 ký tự.",
      example: 'isStrongPassword("12345678") => true\nisStrongPassword("123") => false',
      hint: ["Chuỗi có thuộc tính length.", "Ít nhất 8 nghĩa là >= 8."],
      tests: [
        { expression: 'isStrongPassword("12345678")', expected: true },
        { expression: 'isStrongPassword("abcdefghi")', expected: true },
        { expression: 'isStrongPassword("123")', expected: false },
      ],
      solution: "function isStrongPassword(password) {\n  return password.length >= 8;\n}",
    },
    {
      id: "if-11-time",
      group: "If Else",
      title: "If Else 11 - Lời chào theo giờ: greetingByHour",
      context: "Một dashboard muốn đổi lời chào theo thời điểm trong ngày.",
      request: "Tạo hàm greetingByHour nhận hour.",
      result: "Trả về \"Sáng\" nếu hour < 12, \"Chiều\" nếu hour < 18, còn lại \"Tối\".",
      example: 'greetingByHour(9) => "Sáng"\ngreetingByHour(20) => "Tối"',
      hint: ["Kiểm tra từ đầu ngày tới cuối ngày.", "hour nhỏ hơn 12 là sáng."],
      tests: [
        { expression: "greetingByHour(9)", expected: "Sáng" },
        { expression: "greetingByHour(15)", expected: "Chiều" },
        { expression: "greetingByHour(20)", expected: "Tối" },
      ],
      solution: 'function greetingByHour(hour) {\n  if (hour < 12) return "Sáng";\n  if (hour < 18) return "Chiều";\n  return "Tối";\n}',
    },
    {
      id: "if-12-leap-year",
      group: "If Else",
      title: "If Else 12 - Năm nhuận: isLeapYear",
      context: "Một app lịch cần biết năm có tháng 2 kéo dài 29 ngày hay không.",
      request: "Tạo hàm isLeapYear nhận year.",
      result: "Trả về true nếu year chia hết cho 400 hoặc chia hết cho 4 nhưng không chia hết cho 100.",
      example: "isLeapYear(2024) => true\nisLeapYear(1900) => false",
      hint: ["Dùng % để kiểm tra chia hết.", "Cần kết hợp && và ||.", "Năm chia hết cho 400 chắc chắn là năm nhuận."],
      tests: [
        { expression: "isLeapYear(2024)", expected: true },
        { expression: "isLeapYear(1900)", expected: false },
        { expression: "isLeapYear(2000)", expected: true },
      ],
      solution: "function isLeapYear(year) {\n  return year % 400 === 0 || (year % 4 === 0 && year % 100 !== 0);\n}",
    },
    {
      id: "if-13-min",
      group: "If Else",
      title: "If Else 13 - Nhỏ nhất: min",
      context: "Một app so sánh giá cần lấy giá thấp hơn giữa hai cửa hàng.",
      request: "Tạo hàm min nhận a và b.",
      result: "Trả về số nhỏ hơn.",
      example: "min(3, 9) => 3\nmin(10, 2) => 2",
      hint: ["So sánh a < b.", "Nếu đúng trả về a, ngược lại trả về b."],
      tests: [
        { expression: "min(3, 9)", expected: 3 },
        { expression: "min(10, 2)", expected: 2 },
        { expression: "min(5, 5)", expected: 5 },
      ],
      solution: "function min(a, b) {\n  if (a < b) return a;\n  return b;\n}",
    },
    {
      id: "if-14-range",
      group: "If Else",
      title: "If Else 14 - Trong khoảng: isInRange",
      context: "Một hệ thống cảm biến chỉ chấp nhận giá trị nằm trong khoảng an toàn.",
      request: "Tạo hàm isInRange nhận value, min và max.",
      result: "Trả về true nếu value nằm trong khoảng từ min đến max, tính cả hai đầu.",
      example: "isInRange(5, 1, 10) => true\nisInRange(11, 1, 10) => false",
      hint: ["Cần value >= min và value <= max.", "Dùng && để hai điều kiện cùng đúng."],
      tests: [
        { expression: "isInRange(5, 1, 10)", expected: true },
        { expression: "isInRange(1, 1, 10)", expected: true },
        { expression: "isInRange(11, 1, 10)", expected: false },
      ],
      solution: "function isInRange(value, min, max) {\n  return value >= min && value <= max;\n}",
    },
    {
      id: "if-15-nested-login",
      group: "If Else",
      title: "If Else 15 - Điều kiện lồng nhau: loginMessage",
      context: "Một app đăng nhập muốn báo lỗi rõ hơn cho người dùng.",
      request: "Tạo hàm loginMessage nhận username và password.",
      result: "Nếu username rỗng trả về \"Thiếu username\". Nếu password rỗng trả về \"Thiếu password\". Còn lại trả về \"Đủ thông tin\".",
      example: 'loginMessage("", "123") => "Thiếu username"\nloginMessage("an", "") => "Thiếu password"',
      hint: ["Kiểm tra username trước.", "Sau đó mới kiểm tra password.", "Chuỗi rỗng là \"\"."],
      tests: [
        { expression: 'loginMessage("", "123")', expected: "Thiếu username" },
        { expression: 'loginMessage("an", "")', expected: "Thiếu password" },
        { expression: 'loginMessage("an", "123")', expected: "Đủ thông tin" },
      ],
      solution: 'function loginMessage(username, password) {\n  if (username === "") return "Thiếu username";\n  if (password === "") return "Thiếu password";\n  return "Đủ thông tin";\n}',
    },
    {
      id: "if-16-bmi",
      group: "If Else",
      title: "If Else 16 - Phân loại BMI: bmiCategory",
      context: "Một app sức khỏe cần phân loại chỉ số BMI.",
      request: "Tạo hàm bmiCategory nhận bmi.",
      result: "Trả về \"Gầy\" nếu bmi < 18.5, \"Bình thường\" nếu bmi < 25, \"Thừa cân\" nếu bmi < 30, còn lại \"Béo phì\".",
      example: 'bmiCategory(22) => "Bình thường"',
      hint: ["Kiểm tra từ ngưỡng thấp lên.", "Nếu bmi nhỏ hơn 18.5 thì không cần xét các ngưỡng sau."],
      tests: [
        { expression: "bmiCategory(17)", expected: "Gầy" },
        { expression: "bmiCategory(22)", expected: "Bình thường" },
        { expression: "bmiCategory(27)", expected: "Thừa cân" },
        { expression: "bmiCategory(31)", expected: "Béo phì" },
      ],
      solution: 'function bmiCategory(bmi) {\n  if (bmi < 18.5) return "Gầy";\n  if (bmi < 25) return "Bình thường";\n  if (bmi < 30) return "Thừa cân";\n  return "Béo phì";\n}',
    },
    {
      id: "if-17-triangle",
      group: "If Else",
      title: "If Else 17 - Tam giác hợp lệ: isTriangle",
      context: "Một app hình học cần kiểm tra ba cạnh có tạo được tam giác hay không.",
      request: "Tạo hàm isTriangle nhận a, b và c.",
      result: "Trả về true nếu tổng hai cạnh bất kỳ lớn hơn cạnh còn lại.",
      example: "isTriangle(3, 4, 5) => true\nisTriangle(1, 2, 3) => false",
      hint: ["Cần kiểm tra 3 điều kiện.", "a + b > c, a + c > b, b + c > a.", "Dùng && để tất cả cùng đúng."],
      tests: [
        { expression: "isTriangle(3, 4, 5)", expected: true },
        { expression: "isTriangle(1, 2, 3)", expected: false },
        { expression: "isTriangle(5, 5, 5)", expected: true },
      ],
      solution: "function isTriangle(a, b, c) {\n  return a + b > c && a + c > b && b + c > a;\n}",
    },
    {
      id: "if-18-month-days",
      group: "If Else",
      title: "If Else 18 - Số ngày trong tháng: daysInMonth",
      context: "Một app lịch đơn giản cần biết tháng có bao nhiêu ngày, chưa xét năm nhuận.",
      request: "Tạo hàm daysInMonth nhận month.",
      result: "Trả về 31, 30 hoặc 28 tùy tháng.",
      example: "daysInMonth(1) => 31\ndaysInMonth(2) => 28",
      hint: ["Tháng 2 có 28 ngày.", "Các tháng 4, 6, 9, 11 có 30 ngày.", "Các tháng còn lại có 31 ngày."],
      tests: [
        { expression: "daysInMonth(1)", expected: 31 },
        { expression: "daysInMonth(2)", expected: 28 },
        { expression: "daysInMonth(4)", expected: 30 },
      ],
      solution: "function daysInMonth(month) {\n  if (month === 2) return 28;\n  if (month === 4 || month === 6 || month === 9 || month === 11) return 30;\n  return 31;\n}",
    },
    {
      id: "if-19-vowel",
      group: "If Else",
      title: "If Else 19 - Nguyên âm: isVowel",
      context: "Một app học tiếng Anh cần kiểm tra ký tự có phải nguyên âm hay không.",
      request: "Tạo hàm isVowel nhận char.",
      result: "Trả về true nếu char là a, e, i, o hoặc u.",
      example: 'isVowel("a") => true\nisVowel("b") => false',
      hint: ["Tạo chuỗi \"aeiou\".", "Dùng includes để kiểm tra char có nằm trong chuỗi đó không."],
      tests: [
        { expression: 'isVowel("a")', expected: true },
        { expression: 'isVowel("u")', expected: true },
        { expression: 'isVowel("b")', expected: false },
      ],
      solution: 'function isVowel(char) {\n  return "aeiou".includes(char);\n}',
    },
    {
      id: "if-20-role",
      group: "If Else",
      title: "If Else 20 - Quyền người dùng: canEdit",
      context: "Một hệ thống quản trị chỉ cho admin và editor sửa bài viết.",
      request: "Tạo hàm canEdit nhận role.",
      result: "Trả về true nếu role là \"admin\" hoặc \"editor\".",
      example: 'canEdit("admin") => true\ncanEdit("user") => false',
      hint: ["Có hai role được phép.", "Dùng || để chỉ cần một trong hai điều kiện đúng."],
      tests: [
        { expression: 'canEdit("admin")', expected: true },
        { expression: 'canEdit("editor")', expected: true },
        { expression: 'canEdit("user")', expected: false },
      ],
      solution: 'function canEdit(role) {\n  return role === "admin" || role === "editor";\n}',
    },
  ];

  const loopSpecs = [
    ["loop-01-one-to-n", "Loop 01 - Tạo dãy 1 đến n: numbersFromOneToN", "Một app bài tập cần tạo danh sách số từ 1 đến n.", "Tạo hàm numbersFromOneToN nhận n.", "Trả về mảng các số từ 1 đến n.", "numbersFromOneToN(5) => [1, 2, 3, 4, 5]", ["Dùng vòng lặp bắt đầu từ 1.", "Mỗi vòng thêm số hiện tại vào mảng kết quả."], [{ expression: "numbersFromOneToN(5)", expected: [1, 2, 3, 4, 5] }, { expression: "numbersFromOneToN(1)", expected: [1] }], "function numbersFromOneToN(n) {\n  const result = [];\n  for (let i = 1; i <= n; i++) result.push(i);\n  return result;\n}"],
    ["loop-02-sum-to-n", "Loop 02 - Tổng 1 đến n: sumToN", "Một app thống kê cần cộng các số thứ tự từ 1 đến n.", "Tạo hàm sumToN nhận n.", "Trả về tổng từ 1 đến n.", "sumToN(5) => 15", ["Tạo biến total = 0.", "Duyệt i từ 1 đến n.", "Mỗi vòng cộng i vào total."], [{ expression: "sumToN(5)", expected: 15 }, { expression: "sumToN(100)", expected: 5050 }, { expression: "sumToN(1)", expected: 1 }], "function sumToN(n) {\n  let total = 0;\n  for (let i = 1; i <= n; i++) total += i;\n  return total;\n}"],
    ["loop-03-even-to-n", "Loop 03 - Số chẵn đến n: evenNumbersToN", "Một trò chơi cần danh sách các phòng mang số chẵn.", "Tạo hàm evenNumbersToN nhận n.", "Trả về mảng số chẵn từ 1 đến n.", "evenNumbersToN(8) => [2, 4, 6, 8]", ["Duyệt từ 1 đến n.", "Kiểm tra i % 2 === 0.", "Nếu đúng thì push vào result."], [{ expression: "evenNumbersToN(8)", expected: [2, 4, 6, 8] }, { expression: "evenNumbersToN(3)", expected: [2] }], "function evenNumbersToN(n) {\n  const result = [];\n  for (let i = 1; i <= n; i++) {\n    if (i % 2 === 0) result.push(i);\n  }\n  return result;\n}"],
    ["loop-04-odd-to-n", "Loop 04 - Số lẻ đến n: oddNumbersToN", "Một app chia đội cần lấy các số thứ tự lẻ.", "Tạo hàm oddNumbersToN nhận n.", "Trả về mảng số lẻ từ 1 đến n.", "oddNumbersToN(7) => [1, 3, 5, 7]", ["Số lẻ là số chia 2 dư 1.", "Duyệt từ 1 đến n và lọc bằng if."], [{ expression: "oddNumbersToN(7)", expected: [1, 3, 5, 7] }, { expression: "oddNumbersToN(2)", expected: [1] }], "function oddNumbersToN(n) {\n  const result = [];\n  for (let i = 1; i <= n; i++) {\n    if (i % 2 !== 0) result.push(i);\n  }\n  return result;\n}"],
    ["loop-05-factorial", "Loop 05 - Giai thừa: factorial", "Một bài toán tổ hợp cần tính tích từ 1 đến n.", "Tạo hàm factorial nhận n.", "Trả về n giai thừa.", "factorial(5) => 120", ["Tạo biến result = 1.", "Duyệt i từ 1 đến n.", "Nhân result với i sau mỗi vòng."], [{ expression: "factorial(5)", expected: 120 }, { expression: "factorial(1)", expected: 1 }, { expression: "factorial(3)", expected: 6 }], "function factorial(n) {\n  let result = 1;\n  for (let i = 1; i <= n; i++) result *= i;\n  return result;\n}"],
    ["loop-06-countdown", "Loop 06 - Đếm ngược: countdown", "Một app hẹn giờ cần tạo danh sách số đếm ngược.", "Tạo hàm countdown nhận n.", "Trả về mảng từ n giảm về 1.", "countdown(4) => [4, 3, 2, 1]", ["Vòng lặp có thể giảm i.", "Bắt đầu từ n và chạy khi i >= 1."], [{ expression: "countdown(4)", expected: [4, 3, 2, 1] }, { expression: "countdown(1)", expected: [1] }], "function countdown(n) {\n  const result = [];\n  for (let i = n; i >= 1; i--) result.push(i);\n  return result;\n}"],
    ["loop-07-repeat-text", "Loop 07 - Lặp chuỗi: repeatText", "Một app thông báo cần lặp lại một ký tự để tạo vạch phân cách.", "Tạo hàm repeatText nhận text và times.", "Trả về text được lặp times lần.", 'repeatText("ha", 3) => "hahaha"', ["Tạo chuỗi result rỗng.", "Mỗi vòng cộng thêm text vào result."], [{ expression: 'repeatText("ha", 3)', expected: "hahaha" }, { expression: 'repeatText("*", 5)', expected: "*****" }, { expression: 'repeatText("x", 0)', expected: "" }], "function repeatText(text, times) {\n  let result = \"\";\n  for (let i = 0; i < times; i++) result += text;\n  return result;\n}"],
    ["loop-08-count-char", "Loop 08 - Đếm ký tự: countChar", "Một công cụ văn bản cần đếm một ký tự xuất hiện bao nhiêu lần.", "Tạo hàm countChar nhận text và char.", "Trả về số lần char xuất hiện trong text.", 'countChar("banana", "a") => 3', ["Tạo count = 0.", "Duyệt từng ký tự trong text.", "Nếu ký tự hiện tại bằng char thì tăng count."], [{ expression: 'countChar("banana", "a")', expected: 3 }, { expression: 'countChar("hello", "l")', expected: 2 }, { expression: 'countChar("abc", "z")', expected: 0 }], "function countChar(text, char) {\n  let count = 0;\n  for (let item of text) {\n    if (item === char) count++;\n  }\n  return count;\n}"],
    ["loop-09-reverse-loop", "Loop 09 - Đảo chuỗi bằng vòng lặp: reverseByLoop", "Một trò chơi chữ cần đảo ngược chuỗi mà không dùng reverse().", "Tạo hàm reverseByLoop nhận text.", "Trả về chuỗi đảo ngược.", 'reverseByLoop("code") => "edoc"', ["Duyệt từ cuối chuỗi về đầu.", "Mỗi vòng cộng ký tự vào result."], [{ expression: 'reverseByLoop("code")', expected: "edoc" }, { expression: 'reverseByLoop("abc")', expected: "cba" }], "function reverseByLoop(text) {\n  let result = \"\";\n  for (let i = text.length - 1; i >= 0; i--) result += text[i];\n  return result;\n}"],
    ["loop-10-multiplication", "Loop 10 - Bảng nhân: multiplicationTable", "Một app học toán cần tạo bảng nhân của một số.", "Tạo hàm multiplicationTable nhận n.", "Trả về mảng gồm n * 1 đến n * 10.", "multiplicationTable(3) => [3, 6, 9, ..., 30]", ["Duyệt i từ 1 đến 10.", "Mỗi vòng push n * i vào result."], [{ expression: "multiplicationTable(3)", expected: [3, 6, 9, 12, 15, 18, 21, 24, 27, 30] }, { expression: "multiplicationTable(1)", expected: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }], "function multiplicationTable(n) {\n  const result = [];\n  for (let i = 1; i <= 10; i++) result.push(n * i);\n  return result;\n}"],
    ["loop-11-sum-even", "Loop 11 - Tổng số chẵn: sumEvenToN", "Một báo cáo chỉ muốn cộng các mã đơn hàng chẵn.", "Tạo hàm sumEvenToN nhận n.", "Trả về tổng các số chẵn từ 1 đến n.", "sumEvenToN(6) => 12", ["Duyệt từ 1 đến n.", "Nếu i là số chẵn thì cộng vào total."], [{ expression: "sumEvenToN(6)", expected: 12 }, { expression: "sumEvenToN(10)", expected: 30 }, { expression: "sumEvenToN(1)", expected: 0 }], "function sumEvenToN(n) {\n  let total = 0;\n  for (let i = 1; i <= n; i++) {\n    if (i % 2 === 0) total += i;\n  }\n  return total;\n}"],
    ["loop-12-prime", "Loop 12 - Số nguyên tố: isPrime", "Một bài toán số học cần kiểm tra số nguyên tố.", "Tạo hàm isPrime nhận n.", "Trả về true nếu n là số nguyên tố.", "isPrime(7) => true\nisPrime(9) => false", ["Số nhỏ hơn 2 không phải nguyên tố.", "Duyệt i từ 2 đến n - 1.", "Nếu n chia hết cho i thì không phải nguyên tố."], [{ expression: "isPrime(7)", expected: true }, { expression: "isPrime(9)", expected: false }, { expression: "isPrime(1)", expected: false }], "function isPrime(n) {\n  if (n < 2) return false;\n  for (let i = 2; i < n; i++) {\n    if (n % i === 0) return false;\n  }\n  return true;\n}"],
    ["loop-13-primes-to-n", "Loop 13 - Danh sách nguyên tố: primesToN", "Một app học toán cần liệt kê các số nguyên tố nhỏ.", "Tạo hàm primesToN nhận n.", "Trả về mảng các số nguyên tố từ 2 đến n.", "primesToN(10) => [2, 3, 5, 7]", ["Có thể viết hàm phụ kiểm tra nguyên tố.", "Duyệt từng số và push số nguyên tố vào result."], [{ expression: "primesToN(10)", expected: [2, 3, 5, 7] }, { expression: "primesToN(3)", expected: [2, 3] }], "function primesToN(n) {\n  const result = [];\n  for (let number = 2; number <= n; number++) {\n    let prime = true;\n    for (let i = 2; i < number; i++) {\n      if (number % i === 0) prime = false;\n    }\n    if (prime) result.push(number);\n  }\n  return result;\n}"],
    ["loop-14-fizzbuzz", "Loop 14 - FizzBuzz: fizzBuzz", "Một bài luyện kinh điển giúp quen điều kiện trong vòng lặp.", "Tạo hàm fizzBuzz nhận n.", "Trả về mảng từ 1 đến n, thay số chia hết cho 3 bằng Fizz, chia hết cho 5 bằng Buzz, chia hết cho cả hai bằng FizzBuzz.", "fizzBuzz(5) => [1, 2, \"Fizz\", 4, \"Buzz\"]", ["Kiểm tra chia hết cho 15 trước.", "Sau đó kiểm tra 3 và 5.", "Các số còn lại giữ nguyên."], [{ expression: "fizzBuzz(5)", expected: [1, 2, "Fizz", 4, "Buzz"] }, { expression: "fizzBuzz(15)[14]", expected: "FizzBuzz" }], "function fizzBuzz(n) {\n  const result = [];\n  for (let i = 1; i <= n; i++) {\n    if (i % 15 === 0) result.push(\"FizzBuzz\");\n    else if (i % 3 === 0) result.push(\"Fizz\");\n    else if (i % 5 === 0) result.push(\"Buzz\");\n    else result.push(i);\n  }\n  return result;\n}"],
    ["loop-15-star-line", "Loop 15 - Dòng sao: starLine", "Một bài vẽ console cần tạo một dòng ký tự sao.", "Tạo hàm starLine nhận n.", "Trả về chuỗi gồm n dấu *.", "starLine(4) => \"****\"", ["Tạo chuỗi rỗng.", "Lặp n lần và cộng thêm dấu *."], [{ expression: "starLine(4)", expected: "****" }, { expression: "starLine(1)", expected: "*" }, { expression: "starLine(0)", expected: "" }], "function starLine(n) {\n  let result = \"\";\n  for (let i = 0; i < n; i++) result += \"*\";\n  return result;\n}"],
    ["loop-16-triangle", "Loop 16 - Tam giác sao: starTriangle", "Một bài luyện vòng lặp cần tạo tam giác sao nhiều dòng.", "Tạo hàm starTriangle nhận n.", "Trả về chuỗi tam giác sao, mỗi dòng nhiều hơn một dấu *.", "starTriangle(3) => \"*\\n**\\n***\"", ["Cần vòng lặp dòng từ 1 đến n.", "Mỗi dòng có số sao bằng số dòng.", "Ghép các dòng bằng ký tự xuống dòng \\n."], [{ expression: "starTriangle(3)", expected: "*\n**\n***" }, { expression: "starTriangle(1)", expected: "*" }], "function starTriangle(n) {\n  let result = \"\";\n  for (let i = 1; i <= n; i++) {\n    result += \"*\".repeat(i);\n    if (i < n) result += \"\\n\";\n  }\n  return result;\n}"],
    ["loop-17-pyramid", "Loop 17 - Kim tự tháp: pyramid", "Một bài luyện nâng cao cần căn giữa các dòng sao.", "Tạo hàm pyramid nhận n.", "Trả về chuỗi kim tự tháp sao cao n dòng.", "pyramid(3) => \"  *\\n ***\\n*****\"", ["Mỗi dòng có khoảng trắng phía trước.", "Dòng i có n - i khoảng trắng và 2 * i - 1 dấu sao.", "Ghép dòng bằng \\n."], [{ expression: "pyramid(3)", expected: "  *\n ***\n*****" }, { expression: "pyramid(1)", expected: "*" }], "function pyramid(n) {\n  let result = \"\";\n  for (let i = 1; i <= n; i++) {\n    result += \" \".repeat(n - i) + \"*\".repeat(2 * i - 1);\n    if (i < n) result += \"\\n\";\n  }\n  return result;\n}"],
    ["loop-18-digits", "Loop 18 - Tổng chữ số: sumDigits", "Một app số học cần cộng từng chữ số trong một số.", "Tạo hàm sumDigits nhận n.", "Trả về tổng các chữ số của n.", "sumDigits(123) => 6", ["Đổi số thành chuỗi bằng String(n).", "Duyệt từng ký tự.", "Đổi ký tự về số bằng Number(char)."], [{ expression: "sumDigits(123)", expected: 6 }, { expression: "sumDigits(9005)", expected: 14 }], "function sumDigits(n) {\n  let total = 0;\n  for (let char of String(n)) total += Number(char);\n  return total;\n}"],
    ["loop-19-find-first-even", "Loop 19 - Tìm số chẵn đầu tiên: firstEven", "Một hệ thống cần lấy mã chẵn đầu tiên trong danh sách.", "Tạo hàm firstEven nhận numbers.", "Trả về số chẵn đầu tiên; nếu không có thì trả về null.", "firstEven([1, 3, 4, 6]) => 4", ["Duyệt từng số.", "Gặp số chẵn thì return ngay.", "Duyệt hết mà không thấy thì return null."], [{ expression: "firstEven([1, 3, 4, 6])", expected: 4 }, { expression: "firstEven([1, 3])", expected: null }, { expression: "firstEven([8, 10])", expected: 8 }], "function firstEven(numbers) {\n  for (let number of numbers) {\n    if (number % 2 === 0) return number;\n  }\n  return null;\n}"],
    ["loop-20-running-total", "Loop 20 - Tổng tích lũy: runningTotal", "Một app tài chính cần biết tổng tiền sau từng giao dịch.", "Tạo hàm runningTotal nhận numbers.", "Trả về mảng tổng tích lũy sau mỗi phần tử.", "runningTotal([2, 3, 5]) => [2, 5, 10]", ["Tạo total = 0 và result = [].", "Mỗi vòng cộng số hiện tại vào total.", "Push total vào result."], [{ expression: "runningTotal([2, 3, 5])", expected: [2, 5, 10] }, { expression: "runningTotal([1, -1, 4])", expected: [1, 0, 4] }], "function runningTotal(numbers) {\n  let total = 0;\n  const result = [];\n  for (let number of numbers) {\n    total += number;\n    result.push(total);\n  }\n  return result;\n}"],
  ];

  const functionSpecs = [
    ["fn-01-add", "Function 01 - Hàm cộng: add", "Một app tính nhanh cần cộng hai số người dùng nhập.", "Tạo hàm add nhận a và b.", "Trả về tổng của a và b.", "add(2, 3) => 5", ["Hàm cần nhận hai tham số.", "Bên trong trả về a + b."], [{ expression: "add(2, 3)", expected: 5 }, { expression: "add(-1, 6)", expected: 5 }], "function add(a, b) {\n  return a + b;\n}"],
    ["fn-02-subtract", "Function 02 - Hàm trừ: subtract", "Một cửa hàng cần tính số tiền còn lại sau giảm giá.", "Tạo hàm subtract nhận a và b.", "Trả về a trừ b.", "subtract(8, 3) => 5", ["Phép trừ dùng dấu -.", "Chú ý không đảo b - a."], [{ expression: "subtract(8, 3)", expected: 5 }, { expression: "subtract(4, 9)", expected: -5 }], "function subtract(a, b) {\n  return a - b;\n}"],
    ["fn-03-multiply", "Function 03 - Hàm nhân: multiply", "Một giỏ hàng cần tính giá nhân số lượng.", "Tạo hàm multiply nhận a và b.", "Trả về a nhân b.", "multiply(4, 5) => 20", ["Phép nhân dùng dấu *.", "Return kết quả phép nhân."], [{ expression: "multiply(4, 5)", expected: 20 }, { expression: "multiply(-2, 3)", expected: -6 }], "function multiply(a, b) {\n  return a * b;\n}"],
    ["fn-04-divide", "Function 04 - Hàm chia: divide", "Một app chia tiền cần chia tổng tiền cho số người.", "Tạo hàm divide nhận a và b.", "Trả về a chia b.", "divide(10, 2) => 5", ["Phép chia dùng dấu /.", "Bài này không cần xử lý chia cho 0."], [{ expression: "divide(10, 2)", expected: 5 }, { expression: "divide(9, 3)", expected: 3 }], "function divide(a, b) {\n  return a / b;\n}"],
    ["fn-05-square", "Function 05 - Bình phương: square", "Một app hình học cần tính số mũ 2 của cạnh.", "Tạo hàm square nhận n.", "Trả về n nhân chính nó.", "square(4) => 16", ["Bình phương là n * n.", "Có thể viết function declaration, expression hoặc arrow."], [{ expression: "square(4)", expected: 16 }, { expression: "square(-3)", expected: 9 }], "function square(n) {\n  return n * n;\n}"],
    ["fn-06-cube", "Function 06 - Lập phương: cube", "Một bài toán thể tích cần tính số mũ 3.", "Tạo hàm cube nhận n.", "Trả về n * n * n.", "cube(3) => 27", ["Lập phương là nhân số đó ba lần.", "Cẩn thận với số âm."], [{ expression: "cube(3)", expected: 27 }, { expression: "cube(-2)", expected: -8 }], "function cube(n) {\n  return n * n * n;\n}"],
    ["fn-07-is-even", "Function 07 - Hàm boolean: isEvenNumber", "Một hệ thống cần đóng gói logic kiểm tra số chẵn thành hàm dùng lại.", "Tạo hàm isEvenNumber nhận n.", "Trả về true nếu n chẵn.", "isEvenNumber(8) => true", ["Dùng % để lấy phần dư.", "Biểu thức n % 2 === 0 tự trả về boolean."], [{ expression: "isEvenNumber(8)", expected: true }, { expression: "isEvenNumber(5)", expected: false }], "function isEvenNumber(n) {\n  return n % 2 === 0;\n}"],
    ["fn-08-full-name", "Function 08 - Ghép tên: makeFullName", "Một form hồ sơ lưu riêng họ và tên.", "Tạo hàm makeFullName nhận firstName và lastName.", "Trả về chuỗi họ tên đầy đủ có dấu cách ở giữa.", 'makeFullName("An", "Le") => "An Le"', ["Ghép firstName, dấu cách, rồi lastName.", "Dấu cách là chuỗi \" \"."], [{ expression: 'makeFullName("An", "Le")', expected: "An Le" }, { expression: 'makeFullName("Minh", "Tran")', expected: "Minh Tran" }], "function makeFullName(firstName, lastName) {\n  return firstName + \" \" + lastName;\n}"],
    ["fn-09-default-name", "Function 09 - Giá trị mặc định: greetUser", "Một website muốn chào khách chưa đăng nhập bằng tên Khách.", "Tạo hàm greetUser nhận name.", "Nếu name là chuỗi rỗng, trả về \"Xin chào, Khách\". Ngược lại trả về \"Xin chào, [name]\".", 'greetUser("") => "Xin chào, Khách"', ["Dùng if để kiểm tra chuỗi rỗng.", "Sau đó ghép chuỗi lời chào."], [{ expression: 'greetUser("")', expected: "Xin chào, Khách" }, { expression: 'greetUser("An")', expected: "Xin chào, An" }], "function greetUser(name) {\n  if (name === \"\") return \"Xin chào, Khách\";\n  return \"Xin chào, \" + name;\n}"],
    ["fn-10-average", "Function 10 - Hàm gọi hàm: average", "Một lớp học có hàm tính tổng và muốn dùng lại để tính trung bình.", "Tạo hàm sum nhận a, b, c và hàm average nhận a, b, c.", "average trả về trung bình của ba số bằng cách dùng sum.", "average(6, 7, 8) => 7", ["Viết sum trước.", "Trong average, gọi sum(a, b, c) rồi chia 3."], [{ expression: "sum(1, 2, 3)", expected: 6 }, { expression: "average(6, 7, 8)", expected: 7 }], "function sum(a, b, c) {\n  return a + b + c;\n}\n\nfunction average(a, b, c) {\n  return sum(a, b, c) / 3;\n}"],
    ["fn-11-tax", "Function 11 - Tách logic: calculateTax", "Một app lương cần tính thuế 10% từ lương gốc.", "Tạo hàm calculateTax nhận salary.", "Trả về 10% của salary.", "calculateTax(1000) => 100", ["10% tương đương 0.1.", "Thuế = salary * 0.1."], [{ expression: "calculateTax(1000)", expected: 100 }, { expression: "calculateTax(2500)", expected: 250 }], "function calculateTax(salary) {\n  return salary * 0.1;\n}"],
    ["fn-12-net-salary", "Function 12 - Hàm gọi hàm: netSalary", "Một app lương cần trừ thuế khỏi lương gốc.", "Tạo calculateTax và netSalary.", "netSalary trả về salary trừ tiền thuế.", "netSalary(1000) => 900", ["calculateTax trả về salary * 0.1.", "netSalary gọi calculateTax(salary)."], [{ expression: "calculateTax(1000)", expected: 100 }, { expression: "netSalary(1000)", expected: 900 }], "function calculateTax(salary) {\n  return salary * 0.1;\n}\n\nfunction netSalary(salary) {\n  return salary - calculateTax(salary);\n}"],
    ["fn-13-cm-meter", "Function 13 - Đổi đơn vị: cmToMeter", "Một app đo đạc nhận cm nhưng cần hiển thị mét.", "Tạo hàm cmToMeter nhận cm.", "Trả về cm chia 100.", "cmToMeter(250) => 2.5", ["1 mét bằng 100 cm.", "Đổi cm sang mét bằng cách chia 100."], [{ expression: "cmToMeter(250)", expected: 2.5 }, { expression: "cmToMeter(100)", expected: 1 }], "function cmToMeter(cm) {\n  return cm / 100;\n}"],
    ["fn-14-format-money", "Function 14 - Định dạng tiền: formatMoney", "Một màn hình thanh toán cần hiển thị số tiền kèm đơn vị.", "Tạo hàm formatMoney nhận amount.", "Trả về chuỗi \"[amount] VND\".", 'formatMoney(5000) => "5000 VND"', ["Ghép amount với chuỗi \" VND\".", "Nhớ có dấu cách trước VND."], [{ expression: "formatMoney(5000)", expected: "5000 VND" }, { expression: "formatMoney(0)", expected: "0 VND" }], "function formatMoney(amount) {\n  return amount + \" VND\";\n}"],
    ["fn-15-arrow-double", "Function 15 - Arrow function: double", "Một app điểm thưởng cần nhân đôi điểm của khách.", "Tạo hàm double nhận n bằng cách nào cũng được.", "Trả về n * 2.", "double(5) => 10", ["Bạn có thể viết arrow function nếu muốn luyện cú pháp gọn.", "Kết quả chỉ cần đúng."], [{ expression: "double(5)", expected: 10 }, { expression: "double(-4)", expected: -8 }], "const double = n => n * 2;"],
    ["fn-16-expression", "Function 16 - Function expression: triple", "Một bài luyện muốn bạn coi hàm như giá trị gán vào biến.", "Tạo hàm triple nhận n bằng cách nào cũng được.", "Trả về n * 3.", "triple(4) => 12", ["Nếu dùng function expression, gán function vào const triple.", "Nếu dùng cách khác mà kết quả đúng thì vẫn qua."], [{ expression: "triple(4)", expected: 12 }, { expression: "triple(-2)", expected: -6 }], "const triple = function(n) {\n  return n * 3;\n};"],
    ["fn-17-absolute", "Function 17 - Giá trị tuyệt đối: absolute", "Một app biểu đồ chỉ cần độ lớn của số, không cần dấu âm.", "Tạo hàm absolute nhận n.", "Trả về giá trị tuyệt đối của n.", "absolute(-5) => 5", ["Nếu n < 0 thì trả về -n.", "Ngược lại trả về n."], [{ expression: "absolute(-5)", expected: 5 }, { expression: "absolute(7)", expected: 7 }, { expression: "absolute(0)", expected: 0 }], "function absolute(n) {\n  if (n < 0) return -n;\n  return n;\n}"],
    ["fn-18-clamp", "Function 18 - Giới hạn giá trị: clamp", "Một thanh âm lượng chỉ cho giá trị nằm giữa min và max.", "Tạo hàm clamp nhận value, min và max.", "Nếu value nhỏ hơn min trả về min, nếu lớn hơn max trả về max, còn lại trả về value.", "clamp(120, 0, 100) => 100", ["Xử lý thấp hơn min trước.", "Rồi xử lý cao hơn max.", "Nếu không rơi vào hai trường hợp đó thì value hợp lệ."], [{ expression: "clamp(120, 0, 100)", expected: 100 }, { expression: "clamp(-5, 0, 100)", expected: 0 }, { expression: "clamp(50, 0, 100)", expected: 50 }], "function clamp(value, min, max) {\n  if (value < min) return min;\n  if (value > max) return max;\n  return value;\n}"],
    ["fn-19-compose", "Function 19 - Tách chương trình: finalBill", "Một hóa đơn cần tính tiền hàng, giảm giá rồi cộng phí ship.", "Tạo totalPrice, discountAmount và finalBill.", "finalBill(price, quantity) trả về price * quantity - giảm 10% + 30000.", "finalBill(100000, 2) => 210000", ["totalPrice tính giá * số lượng.", "discountAmount tính 10% của tổng.", "finalBill gọi hai hàm nhỏ rồi cộng phí ship."], [{ expression: "totalPrice(100000, 2)", expected: 200000 }, { expression: "discountAmount(200000)", expected: 20000 }, { expression: "finalBill(100000, 2)", expected: 210000 }], "function totalPrice(price, quantity) {\n  return price * quantity;\n}\n\nfunction discountAmount(total) {\n  return total * 0.1;\n}\n\nfunction finalBill(price, quantity) {\n  const total = totalPrice(price, quantity);\n  return total - discountAmount(total) + 30000;\n}"],
    ["fn-20-inner-function", "Function 20 - Hàm trong hàm: salaryAfterDeductions", "Một app lương muốn giấu các bước tính phụ bên trong hàm chính.", "Tạo hàm salaryAfterDeductions nhận salary.", "Bên trong có thể tách hàm tính bảo hiểm 8% và thuế 10%, trả về lương sau khi trừ cả hai.", "salaryAfterDeductions(1000) => 820", ["Có thể tạo hàm phụ bên trong hàm chính.", "Bảo hiểm = salary * 0.08.", "Thuế = salary * 0.1."], [{ expression: "salaryAfterDeductions(1000)", expected: 820 }, { expression: "salaryAfterDeductions(2000)", expected: 1640 }], "function salaryAfterDeductions(salary) {\n  function insurance(value) {\n    return value * 0.08;\n  }\n\n  function tax(value) {\n    return value * 0.1;\n  }\n\n  return salary - insurance(salary) - tax(salary);\n}"],
  ];

  const arraySpecs = [
    ["array-01-length", "Array 01 - length: countItems", "Một giỏ hàng cần hiển thị có bao nhiêu sản phẩm.", "Tạo hàm countItems nhận arr.", "Trả về số lượng phần tử trong arr.", "countItems([1, 2, 3]) => 3", ["Mảng có thuộc tính length.", "Bài này không cần vòng lặp."], [{ expression: "countItems([1, 2, 3])", expected: 3 }, { expression: "countItems([])", expected: 0 }], "function countItems(arr) {\n  return arr.length;\n}"],
    ["array-02-first", "Array 02 - Phần tử đầu: firstItem", "Một app tin tức cần lấy bài đầu tiên làm bài nổi bật.", "Tạo hàm firstItem nhận arr.", "Trả về phần tử đầu tiên.", "firstItem([\"a\", \"b\"]) => \"a\"", ["Vị trí đầu tiên trong mảng là 0.", "Dùng arr[0]."], [{ expression: 'firstItem(["a", "b"])', expected: "a" }, { expression: "firstItem([7, 8])", expected: 7 }], "function firstItem(arr) {\n  return arr[0];\n}"],
    ["array-03-last", "Array 03 - Phần tử cuối: lastItem", "Một app chat cần lấy tin nhắn mới nhất trong danh sách.", "Tạo hàm lastItem nhận arr.", "Trả về phần tử cuối cùng.", "lastItem([1, 2, 3]) => 3", ["Vị trí cuối là arr.length - 1.", "Dùng ngoặc vuông để lấy phần tử."], [{ expression: "lastItem([1, 2, 3])", expected: 3 }, { expression: 'lastItem(["x", "y"])', expected: "y" }], "function lastItem(arr) {\n  return arr[arr.length - 1];\n}"],
    ["array-04-push", "Array 04 - push: addItem", "Một danh sách mua sắm cần thêm món mới vào cuối danh sách.", "Tạo hàm addItem nhận arr và item.", "Thêm item vào arr rồi trả về arr.", "addItem([\"a\"], \"b\") => [\"a\", \"b\"]", ["Dùng arr.push(item).", "Sau khi push, return arr."], [{ expression: 'addItem(["a"], "b")', expected: ["a", "b"] }, { expression: "addItem([1, 2], 3)", expected: [1, 2, 3] }], "function addItem(arr, item) {\n  arr.push(item);\n  return arr;\n}"],
    ["array-05-includes", "Array 05 - includes: hasItem", "Một app mua sắm cần kiểm tra món đã có trong danh sách chưa.", "Tạo hàm hasItem nhận arr và item.", "Trả về true nếu item có trong arr.", "hasItem([\"a\", \"b\"], \"b\") => true", ["Mảng có phương thức includes.", "includes trả về true hoặc false."], [{ expression: 'hasItem(["a", "b"], "b")', expected: true }, { expression: "hasItem([1, 2], 5)", expected: false }], "function hasItem(arr, item) {\n  return arr.includes(item);\n}"],
    ["array-06-indexof", "Array 06 - indexOf: findIndexOf", "Một playlist cần biết bài hát nằm ở vị trí nào.", "Tạo hàm findIndexOf nhận arr và item.", "Trả về vị trí của item, nếu không có trả về -1.", "findIndexOf([\"a\", \"b\"], \"b\") => 1", ["indexOf trả về vị trí.", "Nếu không tìm thấy, indexOf trả về -1."], [{ expression: 'findIndexOf(["a", "b"], "b")', expected: 1 }, { expression: "findIndexOf([1, 2], 9)", expected: -1 }], "function findIndexOf(arr, item) {\n  return arr.indexOf(item);\n}"],
    ["array-07-sum", "Array 07 - Cộng mảng: sumArray", "Một lớp học cần tính tổng điểm các bài kiểm tra.", "Tạo hàm sumArray nhận numbers.", "Trả về tổng các số trong mảng.", "sumArray([1, 2, 3]) => 6", ["Tạo total = 0.", "Duyệt từng số và cộng vào total."], [{ expression: "sumArray([1, 2, 3])", expected: 6 }, { expression: "sumArray([])", expected: 0 }], "function sumArray(numbers) {\n  let total = 0;\n  for (let number of numbers) total += number;\n  return total;\n}"],
    ["array-08-average", "Array 08 - Trung bình: averageArray", "Một lớp học cần tính điểm trung bình.", "Tạo hàm averageArray nhận numbers.", "Trả về trung bình cộng; nếu mảng rỗng trả về 0.", "averageArray([2, 4, 6]) => 4", ["Tính tổng trước.", "Chia tổng cho numbers.length.", "Nhớ xử lý mảng rỗng."], [{ expression: "averageArray([2, 4, 6])", expected: 4 }, { expression: "averageArray([])", expected: 0 }], "function averageArray(numbers) {\n  if (numbers.length === 0) return 0;\n  let total = 0;\n  for (let number of numbers) total += number;\n  return total / numbers.length;\n}"],
    ["array-09-max", "Array 09 - Tìm lớn nhất: maxArray", "Một bảng điểm cần tìm điểm cao nhất.", "Tạo hàm maxArray nhận numbers.", "Trả về số lớn nhất trong mảng.", "maxArray([3, 9, 4]) => 9", ["Tạm coi phần tử đầu là lớn nhất.", "Duyệt và cập nhật nếu gặp số lớn hơn."], [{ expression: "maxArray([3, 9, 4])", expected: 9 }, { expression: "maxArray([-5, -2, -9])", expected: -2 }], "function maxArray(numbers) {\n  let max = numbers[0];\n  for (let number of numbers) {\n    if (number > max) max = number;\n  }\n  return max;\n}"],
    ["array-10-min", "Array 10 - Tìm nhỏ nhất: minArray", "Một app giá cần tìm giá thấp nhất.", "Tạo hàm minArray nhận numbers.", "Trả về số nhỏ nhất trong mảng.", "minArray([3, 9, 4]) => 3", ["Tạm coi phần tử đầu là nhỏ nhất.", "Duyệt và cập nhật nếu gặp số nhỏ hơn."], [{ expression: "minArray([3, 9, 4])", expected: 3 }, { expression: "minArray([-5, -2, -9])", expected: -9 }], "function minArray(numbers) {\n  let min = numbers[0];\n  for (let number of numbers) {\n    if (number < min) min = number;\n  }\n  return min;\n}"],
    ["array-11-count-even", "Array 11 - Đếm số chẵn: countEven", "Một trò chơi cần biết có bao nhiêu người chơi mang số chẵn.", "Tạo hàm countEven nhận numbers.", "Trả về số lượng số chẵn.", "countEven([1, 2, 4]) => 2", ["Tạo count = 0.", "Nếu number % 2 === 0 thì tăng count."], [{ expression: "countEven([1, 2, 4])", expected: 2 }, { expression: "countEven([1, 3])", expected: 0 }], "function countEven(numbers) {\n  let count = 0;\n  for (let number of numbers) {\n    if (number % 2 === 0) count++;\n  }\n  return count;\n}"],
    ["array-12-filter-even", "Array 12 - Lọc số chẵn: filterEven", "Một hệ thống cần tạo danh sách mới chỉ gồm mã chẵn.", "Tạo hàm filterEven nhận numbers.", "Trả về mảng chỉ gồm số chẵn.", "filterEven([1, 2, 3, 4]) => [2, 4]", ["Tạo result = [].", "Nếu số chẵn thì push vào result."], [{ expression: "filterEven([1, 2, 3, 4])", expected: [2, 4] }, { expression: "filterEven([1, 3])", expected: [] }], "function filterEven(numbers) {\n  const result = [];\n  for (let number of numbers) {\n    if (number % 2 === 0) result.push(number);\n  }\n  return result;\n}"],
    ["array-13-filter-positive", "Array 13 - Lọc số dương: filterPositive", "Một báo cáo tài chính cần lấy các khoản tăng trưởng dương.", "Tạo hàm filterPositive nhận numbers.", "Trả về mảng chỉ gồm số lớn hơn 0.", "filterPositive([-1, 2, 0, 3]) => [2, 3]", ["Số dương là > 0.", "0 không phải số dương trong bài này."], [{ expression: "filterPositive([-1, 2, 0, 3])", expected: [2, 3] }, { expression: "filterPositive([-5, -1])", expected: [] }], "function filterPositive(numbers) {\n  const result = [];\n  for (let number of numbers) {\n    if (number > 0) result.push(number);\n  }\n  return result;\n}"],
    ["array-14-map-double", "Array 14 - Tạo mảng mới: doubleNumbers", "Một chương trình khuyến mãi muốn nhân đôi điểm thưởng.", "Tạo hàm doubleNumbers nhận numbers.", "Trả về mảng mới, mỗi số nhân 2.", "doubleNumbers([1, 2, 3]) => [2, 4, 6]", ["Tạo result = [].", "Với mỗi number, push number * 2."], [{ expression: "doubleNumbers([1, 2, 3])", expected: [2, 4, 6] }, { expression: "doubleNumbers([])", expected: [] }], "function doubleNumbers(numbers) {\n  const result = [];\n  for (let number of numbers) result.push(number * 2);\n  return result;\n}"],
    ["array-15-map-length", "Array 15 - Độ dài chuỗi: wordLengths", "Một công cụ văn bản cần biết mỗi từ dài bao nhiêu ký tự.", "Tạo hàm wordLengths nhận words.", "Trả về mảng độ dài của từng từ.", 'wordLengths(["js", "code"]) => [2, 4]', ["Duyệt từng word.", "word.length là độ dài chuỗi."], [{ expression: 'wordLengths(["js", "code"])', expected: [2, 4] }, { expression: 'wordLengths(["a", "abc"])', expected: [1, 3] }], "function wordLengths(words) {\n  const result = [];\n  for (let word of words) result.push(word.length);\n  return result;\n}"],
    ["array-16-find", "Array 16 - Tìm phần tử: findFirstOver", "Một app điểm cần tìm điểm đầu tiên vượt qua mốc.", "Tạo hàm findFirstOver nhận numbers và limit.", "Trả về số đầu tiên lớn hơn limit; nếu không có trả về null.", "findFirstOver([3, 8, 10], 7) => 8", ["Duyệt từng số.", "Gặp số > limit thì return ngay.", "Không thấy thì return null."], [{ expression: "findFirstOver([3, 8, 10], 7)", expected: 8 }, { expression: "findFirstOver([1, 2], 5)", expected: null }], "function findFirstOver(numbers, limit) {\n  for (let number of numbers) {\n    if (number > limit) return number;\n  }\n  return null;\n}"],
    ["array-17-every", "Array 17 - Kiểm tra tất cả: allPositive", "Một báo cáo cần chắc chắn mọi giá trị đều dương.", "Tạo hàm allPositive nhận numbers.", "Trả về true nếu tất cả số đều lớn hơn 0.", "allPositive([1, 2, 3]) => true", ["Chỉ cần gặp một số <= 0 là false.", "Duyệt hết mà không gặp lỗi thì true."], [{ expression: "allPositive([1, 2, 3])", expected: true }, { expression: "allPositive([1, 0, 3])", expected: false }], "function allPositive(numbers) {\n  for (let number of numbers) {\n    if (number <= 0) return false;\n  }\n  return true;\n}"],
    ["array-18-some", "Array 18 - Kiểm tra tồn tại: hasNegative", "Một hệ thống cần phát hiện có khoản âm trong danh sách hay không.", "Tạo hàm hasNegative nhận numbers.", "Trả về true nếu có ít nhất một số âm.", "hasNegative([1, -2, 3]) => true", ["Gặp số < 0 thì return true.", "Duyệt hết mà không gặp thì false."], [{ expression: "hasNegative([1, -2, 3])", expected: true }, { expression: "hasNegative([1, 2])", expected: false }], "function hasNegative(numbers) {\n  for (let number of numbers) {\n    if (number < 0) return true;\n  }\n  return false;\n}"],
    ["array-19-join", "Array 19 - join: joinWords", "Một app ghi chú cần ghép các từ thành câu.", "Tạo hàm joinWords nhận words.", "Trả về các từ được ghép bằng dấu cách.", 'joinWords(["xin", "chao"]) => "xin chao"', ["Mảng có phương thức join.", "join(\" \") ghép bằng dấu cách."], [{ expression: 'joinWords(["xin", "chao"])', expected: "xin chao" }, { expression: 'joinWords(["a", "b", "c"])', expected: "a b c" }], "function joinWords(words) {\n  return words.join(\" \");\n}"],
    ["array-20-split", "Array 20 - split: splitWords", "Một công cụ văn bản cần tách câu thành các từ.", "Tạo hàm splitWords nhận sentence.", "Trả về mảng các từ, tách theo dấu cách.", 'splitWords("hoc js") => ["hoc", "js"]', ["Chuỗi có phương thức split.", "split(\" \") tách theo dấu cách."], [{ expression: 'splitWords("hoc js")', expected: ["hoc", "js"] }, { expression: 'splitWords("a b c")', expected: ["a", "b", "c"] }], "function splitWords(sentence) {\n  return sentence.split(\" \");\n}"],
    ["array-21-sort-asc", "Array 21 - Sắp xếp tăng: sortAsc", "Một bảng điểm cần sắp xếp điểm từ thấp đến cao.", "Tạo hàm sortAsc nhận numbers.", "Trả về mảng numbers đã sắp xếp tăng dần.", "sortAsc([3, 1, 2]) => [1, 2, 3]", ["Dùng sort với hàm so sánh.", "a - b tạo thứ tự tăng dần."], [{ expression: "sortAsc([3, 1, 2])", expected: [1, 2, 3] }, { expression: "sortAsc([10, 2, 5])", expected: [2, 5, 10] }], "function sortAsc(numbers) {\n  return numbers.sort((a, b) => a - b);\n}"],
    ["array-22-sort-desc", "Array 22 - Sắp xếp giảm: sortDesc", "Một bảng xếp hạng cần điểm cao đứng trước.", "Tạo hàm sortDesc nhận numbers.", "Trả về mảng numbers đã sắp xếp giảm dần.", "sortDesc([3, 1, 2]) => [3, 2, 1]", ["Dùng sort với hàm so sánh.", "b - a tạo thứ tự giảm dần."], [{ expression: "sortDesc([3, 1, 2])", expected: [3, 2, 1] }, { expression: "sortDesc([10, 2, 5])", expected: [10, 5, 2] }], "function sortDesc(numbers) {\n  return numbers.sort((a, b) => b - a);\n}"],
    ["array-23-remove-first", "Array 23 - Bỏ phần tử đầu: removeFirst", "Một hàng đợi cần lấy danh sách còn lại sau khi người đầu tiên được xử lý.", "Tạo hàm removeFirst nhận arr.", "Trả về mảng mới bỏ phần tử đầu tiên.", "removeFirst([1, 2, 3]) => [2, 3]", ["slice(1) lấy từ vị trí 1 đến hết.", "Không cần tự lặp nếu dùng slice."], [{ expression: "removeFirst([1, 2, 3])", expected: [2, 3] }, { expression: 'removeFirst(["a"])', expected: [] }], "function removeFirst(arr) {\n  return arr.slice(1);\n}"],
    ["array-24-remove-last", "Array 24 - Bỏ phần tử cuối: removeLast", "Một danh sách lịch sử cần bỏ thao tác mới nhất.", "Tạo hàm removeLast nhận arr.", "Trả về mảng mới bỏ phần tử cuối cùng.", "removeLast([1, 2, 3]) => [1, 2]", ["slice(0, arr.length - 1) lấy từ đầu tới trước phần tử cuối.", "Trả về mảng mới."], [{ expression: "removeLast([1, 2, 3])", expected: [1, 2] }, { expression: 'removeLast(["a"])', expected: [] }], "function removeLast(arr) {\n  return arr.slice(0, arr.length - 1);\n}"],
    ["array-25-merge", "Array 25 - Gộp mảng: mergeArrays", "Một app cần gộp hai danh sách sản phẩm.", "Tạo hàm mergeArrays nhận a và b.", "Trả về mảng gồm phần tử của a rồi đến b.", "mergeArrays([1, 2], [3]) => [1, 2, 3]", ["Có thể dùng concat.", "a.concat(b) tạo mảng mới."], [{ expression: "mergeArrays([1, 2], [3])", expected: [1, 2, 3] }, { expression: 'mergeArrays(["a"], ["b", "c"])', expected: ["a", "b", "c"] }], "function mergeArrays(a, b) {\n  return a.concat(b);\n}"],
    ["array-26-unique", "Array 26 - Loại trùng: uniqueItems", "Một danh sách tag cần loại bỏ tag bị nhập trùng.", "Tạo hàm uniqueItems nhận arr.", "Trả về mảng mới không có phần tử trùng, giữ thứ tự xuất hiện đầu tiên.", "uniqueItems([1, 2, 1]) => [1, 2]", ["Tạo result = [].", "Chỉ push item nếu result chưa includes item."], [{ expression: "uniqueItems([1, 2, 1])", expected: [1, 2] }, { expression: 'uniqueItems(["a", "a", "b"])', expected: ["a", "b"] }], "function uniqueItems(arr) {\n  const result = [];\n  for (let item of arr) {\n    if (!result.includes(item)) result.push(item);\n  }\n  return result;\n}"],
    ["array-27-flatten", "Array 27 - Làm phẳng mảng: flattenOnce", "Một dữ liệu nhóm nhỏ cần gộp các mảng con thành một mảng.", "Tạo hàm flattenOnce nhận arr.", "Trả về mảng được làm phẳng một cấp.", "flattenOnce([[1, 2], [3]]) => [1, 2, 3]", ["Duyệt từng mảng con.", "Duyệt từng item trong mảng con và push vào result."], [{ expression: "flattenOnce([[1, 2], [3]])", expected: [1, 2, 3] }, { expression: 'flattenOnce([["a"], ["b", "c"]])', expected: ["a", "b", "c"] }], "function flattenOnce(arr) {\n  const result = [];\n  for (let group of arr) {\n    for (let item of group) result.push(item);\n  }\n  return result;\n}"],
    ["array-28-reduce", "Array 28 - reduce: productArray", "Một bài toán cần nhân tất cả hệ số trong mảng.", "Tạo hàm productArray nhận numbers.", "Trả về tích của tất cả số trong mảng; mảng rỗng trả về 1.", "productArray([2, 3, 4]) => 24", ["Tích ban đầu nên là 1.", "Mỗi vòng nhân thêm số hiện tại."], [{ expression: "productArray([2, 3, 4])", expected: 24 }, { expression: "productArray([])", expected: 1 }], "function productArray(numbers) {\n  let result = 1;\n  for (let number of numbers) result *= number;\n  return result;\n}"],
    ["array-29-count-words", "Array 29 - Đếm theo điều kiện: countLongWords", "Một công cụ văn bản cần đếm từ dài hơn một mốc.", "Tạo hàm countLongWords nhận words và minLength.", "Trả về số từ có độ dài lớn hơn minLength.", 'countLongWords(["js", "javascript"], 3) => 1', ["Dùng word.length để đo độ dài.", "Nếu word.length > minLength thì tăng count."], [{ expression: 'countLongWords(["js", "javascript"], 3)', expected: 1 }, { expression: 'countLongWords(["one", "three", "seven"], 4)', expected: 2 }], "function countLongWords(words, minLength) {\n  let count = 0;\n  for (let word of words) {\n    if (word.length > minLength) count++;\n  }\n  return count;\n}"],
    ["array-30-shopping-total", "Array 30 - Mảng object: cartTotal", "Một giỏ hàng lưu mỗi sản phẩm bằng object có price và quantity.", "Tạo hàm cartTotal nhận items.", "Trả về tổng price * quantity của tất cả item.", "cartTotal([{price: 10, quantity: 2}]) => 20", ["Duyệt từng item.", "Mỗi item có item.price và item.quantity.", "Cộng item.price * item.quantity vào total."], [{ expression: "cartTotal([{ price: 10, quantity: 2 }, { price: 5, quantity: 3 }])", expected: 35 }, { expression: "cartTotal([])", expected: 0 }], "function cartTotal(items) {\n  let total = 0;\n  for (let item of items) total += item.price * item.quantity;\n  return total;\n}"],
  ];

  const objectSpecs = [
    ["object-01-user", "Object 01 - Tạo object: user", "Một app hồ sơ cần lưu thông tin người dùng trong một object.", "Tạo object user có name là \"An\" và age là 20.", "Đọc user.name được \"An\" và user.age được 20.", 'user.name => "An"', ["Object dùng cặp ngoặc nhọn {}.", "Thuộc tính viết theo dạng key: value."], [{ expression: "user.name", expected: "An" }, { expression: "user.age", expected: 20 }], "const user = {\n  name: \"An\",\n  age: 20,\n};"],
    ["object-02-read", "Object 02 - Đọc thuộc tính: getUserName", "Một app cần lấy tên từ object user để hiển thị.", "Tạo hàm getUserName nhận user.", "Trả về thuộc tính name của user.", 'getUserName({ name: "Lan" }) => "Lan"', ["Đọc thuộc tính bằng dấu chấm.", "user.name là tên trong object."], [{ expression: 'getUserName({ name: "Lan", age: 18 })', expected: "Lan" }, { expression: 'getUserName({ name: "Minh" })', expected: "Minh" }], "function getUserName(user) {\n  return user.name;\n}"],
    ["object-03-update", "Object 03 - Cập nhật thuộc tính: updateAge", "Một hồ sơ cần cập nhật tuổi mới cho user.", "Tạo hàm updateAge nhận user và newAge.", "Gán user.age bằng newAge rồi trả về user.", "updateAge({name:\"An\", age:20}, 21).age => 21", ["Gán thuộc tính bằng user.age = newAge.", "Sau khi cập nhật thì return user."], [{ expression: "updateAge({ name: \"An\", age: 20 }, 21).age", expected: 21 }, { expression: "updateAge({ name: \"A\", age: 1 }, 5).age", expected: 5 }], "function updateAge(user, newAge) {\n  user.age = newAge;\n  return user;\n}"],
    ["object-04-add", "Object 04 - Thêm thuộc tính: addEmail", "Một form đăng ký cần thêm email vào object user.", "Tạo hàm addEmail nhận user và email.", "Gán user.email bằng email rồi trả về user.", 'addEmail({name:"An"}, "a@gmail.com").email => "a@gmail.com"', ["Có thể thêm thuộc tính mới bằng dấu chấm.", "user.email = email."], [{ expression: 'addEmail({ name: "An" }, "a@gmail.com").email', expected: "a@gmail.com" }, { expression: 'addEmail({}, "x@y.com").email', expected: "x@y.com" }], "function addEmail(user, email) {\n  user.email = email;\n  return user;\n}"],
    ["object-05-method", "Object 05 - Method và this: person.introduce", "Một object cá nhân cần tự giới thiệu tên của nó.", "Tạo object person có name là \"Nam\" và method introduce.", "person.introduce() trả về \"Tôi là Nam\".", 'person.introduce() => "Tôi là Nam"', ["Method là hàm nằm trong object.", "Trong method, this.name trỏ tới name của object đang gọi."], [{ expression: "person.name", expected: "Nam" }, { expression: "person.introduce()", expected: "Tôi là Nam" }], "const person = {\n  name: \"Nam\",\n  introduce: function() {\n    return \"Tôi là \" + this.name;\n  },\n};"],
    ["object-06-product-total", "Object 06 - Tính từ object: productTotal", "Một sản phẩm có price và quantity cần tính thành tiền.", "Tạo hàm productTotal nhận product.", "Trả về product.price * product.quantity.", "productTotal({price: 10, quantity: 3}) => 30", ["Đọc price và quantity từ object.", "Nhân hai giá trị đó."], [{ expression: "productTotal({ price: 10, quantity: 3 })", expected: 30 }, { expression: "productTotal({ price: 5, quantity: 4 })", expected: 20 }], "function productTotal(product) {\n  return product.price * product.quantity;\n}"],
    ["object-07-has-key", "Object 07 - Kiểm tra thuộc tính: hasEmail", "Một app cần biết user đã có email hay chưa.", "Tạo hàm hasEmail nhận user.", "Trả về true nếu user.email không phải undefined.", "hasEmail({email:\"a@b.com\"}) => true", ["Nếu thuộc tính không tồn tại, giá trị là undefined.", "So sánh user.email !== undefined."], [{ expression: 'hasEmail({ email: "a@b.com" })', expected: true }, { expression: 'hasEmail({ name: "An" })', expected: false }], "function hasEmail(user) {\n  return user.email !== undefined;\n}"],
    ["object-08-list-names", "Object 08 - Mảng object: getNames", "Một lớp học lưu danh sách học sinh bằng mảng object.", "Tạo hàm getNames nhận users.", "Trả về mảng name của từng user.", 'getNames([{name:"An"}, {name:"Lan"}]) => ["An", "Lan"]', ["Duyệt từng user trong users.", "Push user.name vào result."], [{ expression: 'getNames([{ name: "An" }, { name: "Lan" }])', expected: ["An", "Lan"] }, { expression: "getNames([])", expected: [] }], "function getNames(users) {\n  const result = [];\n  for (let user of users) result.push(user.name);\n  return result;\n}"],
    ["object-09-filter-price", "Object 09 - Lọc object: expensiveProducts", "Một shop cần lọc sản phẩm có giá cao hơn một mốc.", "Tạo hàm expensiveProducts nhận products và minPrice.", "Trả về mảng sản phẩm có price lớn hơn minPrice.", "expensiveProducts([{price:100}, {price:50}], 80).length => 1", ["Duyệt từng product.", "Nếu product.price > minPrice thì push product."], [{ expression: "expensiveProducts([{ name: \"A\", price: 100 }, { name: \"B\", price: 50 }], 80).length", expected: 1 }, { expression: "expensiveProducts([{ price: 10 }], 80).length", expected: 0 }], "function expensiveProducts(products, minPrice) {\n  const result = [];\n  for (let product of products) {\n    if (product.price > minPrice) result.push(product);\n  }\n  return result;\n}"],
    ["object-10-find-user", "Object 10 - Tìm object: findUserByName", "Một danh bạ cần tìm user theo tên.", "Tạo hàm findUserByName nhận users và name.", "Trả về user đầu tiên có user.name bằng name; nếu không có trả về null.", 'findUserByName([{name:"An"}], "An").name => "An"', ["Duyệt từng user.", "Nếu user.name === name thì return user.", "Không thấy thì return null."], [{ expression: 'findUserByName([{ name: "An" }, { name: "Lan" }], "Lan").name', expected: "Lan" }, { expression: 'findUserByName([{ name: "An" }], "Minh")', expected: null }], "function findUserByName(users, name) {\n  for (let user of users) {\n    if (user.name === name) return user;\n  }\n  return null;\n}"],
    ["object-11-count-active", "Object 11 - Đếm object: countActiveUsers", "Một hệ thống cần biết có bao nhiêu tài khoản đang hoạt động.", "Tạo hàm countActiveUsers nhận users.", "Trả về số user có active là true.", "countActiveUsers([{active:true}, {active:false}]) => 1", ["Tạo count = 0.", "Nếu user.active === true thì tăng count."], [{ expression: "countActiveUsers([{ active: true }, { active: false }, { active: true }])", expected: 2 }, { expression: "countActiveUsers([])", expected: 0 }], "function countActiveUsers(users) {\n  let count = 0;\n  for (let user of users) {\n    if (user.active === true) count++;\n  }\n  return count;\n}"],
    ["object-12-total-stock", "Object 12 - Tính tổng object: totalStock", "Một kho hàng cần tính tổng số lượng tồn.", "Tạo hàm totalStock nhận products.", "Trả về tổng quantity của tất cả product.", "totalStock([{quantity:2}, {quantity:3}]) => 5", ["Tạo total = 0.", "Cộng product.quantity vào total."], [{ expression: "totalStock([{ quantity: 2 }, { quantity: 3 }])", expected: 5 }, { expression: "totalStock([])", expected: 0 }], "function totalStock(products) {\n  let total = 0;\n  for (let product of products) total += product.quantity;\n  return total;\n}"],
    ["object-13-average-score", "Object 13 - Điểm trung bình: averageScore", "Một lớp học lưu điểm trong object student.", "Tạo hàm averageScore nhận student.", "student.scores là mảng số; trả về điểm trung bình.", "averageScore({scores:[8, 10]}) => 9", ["Lấy mảng bằng student.scores.", "Tính tổng rồi chia cho độ dài mảng."], [{ expression: "averageScore({ name: \"An\", scores: [8, 10] })", expected: 9 }, { expression: "averageScore({ scores: [6, 6, 9] })", expected: 7 }], "function averageScore(student) {\n  let total = 0;\n  for (let score of student.scores) total += score;\n  return total / student.scores.length;\n}"],
    ["object-14-best-student", "Object 14 - Tìm object tốt nhất: bestStudent", "Một lớp học cần tìm học sinh có điểm cao nhất.", "Tạo hàm bestStudent nhận students.", "Trả về student có score lớn nhất.", 'bestStudent([{name:"An", score:8}, {name:"Lan", score:9}]).name => "Lan"', ["Tạm coi học sinh đầu tiên là tốt nhất.", "Duyệt và cập nhật nếu score cao hơn."], [{ expression: 'bestStudent([{ name: "An", score: 8 }, { name: "Lan", score: 9 }]).name', expected: "Lan" }, { expression: 'bestStudent([{ name: "A", score: 5 }]).name', expected: "A" }], "function bestStudent(students) {\n  let best = students[0];\n  for (let student of students) {\n    if (student.score > best.score) best = student;\n  }\n  return best;\n}"],
    ["object-15-group-label", "Object 15 - Tạo chuỗi từ object: productLabel", "Một shop cần hiển thị tên sản phẩm kèm giá.", "Tạo hàm productLabel nhận product.", "Trả về chuỗi \"[name] - [price] VND\".", 'productLabel({name:"Áo", price:100}) => "Áo - 100 VND"', ["Đọc product.name và product.price.", "Ghép chuỗi đúng dấu cách và dấu gạch ngang."], [{ expression: 'productLabel({ name: "Áo", price: 100 })', expected: "Áo - 100 VND" }, { expression: 'productLabel({ name: "Giày", price: 500 })', expected: "Giày - 500 VND" }], "function productLabel(product) {\n  return product.name + \" - \" + product.price + \" VND\";\n}"],
    ["object-16-nested", "Object 16 - Object lồng nhau: getCity", "Một hồ sơ người dùng lưu địa chỉ bên trong object address.", "Tạo hàm getCity nhận user.", "Trả về user.address.city.", 'getCity({address:{city:"HCM"}}) => "HCM"', ["Object có thể nằm trong object khác.", "Đi từng cấp bằng dấu chấm."], [{ expression: 'getCity({ address: { city: "HCM" } })', expected: "HCM" }, { expression: 'getCity({ address: { city: "Ha Noi" } })', expected: "Ha Noi" }], "function getCity(user) {\n  return user.address.city;\n}"],
    ["object-17-nested-update", "Object 17 - Cập nhật object lồng nhau: updateCity", "Một app giao hàng cần cập nhật thành phố trong địa chỉ.", "Tạo hàm updateCity nhận user và city.", "Gán user.address.city bằng city rồi trả về user.", 'updateCity({address:{city:"HCM"}}, "Da Nang").address.city => "Da Nang"', ["Truy cập user.address.city.", "Gán giá trị mới rồi return user."], [{ expression: 'updateCity({ address: { city: "HCM" } }, "Da Nang").address.city', expected: "Da Nang" }, { expression: 'updateCity({ address: { city: "A" } }, "B").address.city', expected: "B" }], "function updateCity(user, city) {\n  user.address.city = city;\n  return user;\n}"],
    ["object-18-method-balance", "Object 18 - Method tính toán: account.getBalanceText", "Một ví điện tử cần object tài khoản tự hiển thị số dư.", "Tạo object account có username \"user01\", balance 500000 và method getBalanceText.", "account.getBalanceText() trả về \"user01 còn 500000 VND\".", 'account.getBalanceText() => "user01 còn 500000 VND"', ["Trong method dùng this.username và this.balance.", "Method có thể return chuỗi thay vì console.log."], [{ expression: "account.username", expected: "user01" }, { expression: "account.balance", expected: 500000 }, { expression: "account.getBalanceText()", expected: "user01 còn 500000 VND" }], "const account = {\n  username: \"user01\",\n  balance: 500000,\n  getBalanceText: function() {\n    return this.username + \" còn \" + this.balance + \" VND\";\n  },\n};"],
    ["object-19-cart-names", "Object 19 - Mảng object sang chuỗi: cartNames", "Một giỏ hàng cần hiển thị tên các sản phẩm đã chọn.", "Tạo hàm cartNames nhận items.", "Trả về chuỗi tên sản phẩm, cách nhau bằng dấu phẩy và khoảng trắng.", 'cartNames([{name:"Áo"}, {name:"Giày"}]) => "Áo, Giày"', ["Lấy name của từng item vào mảng names.", "Dùng names.join(\", \")."], [{ expression: 'cartNames([{ name: "Áo" }, { name: "Giày" }])', expected: "Áo, Giày" }, { expression: 'cartNames([{ name: "A" }])', expected: "A" }], "function cartNames(items) {\n  const names = [];\n  for (let item of items) names.push(item.name);\n  return names.join(\", \");\n}"],
    ["object-20-dashboard", "Object 20 - Tổng hợp dữ liệu: dashboardSummary", "Một dashboard cần tóm tắt số user và số user active.", "Tạo hàm dashboardSummary nhận users.", "Trả về object có total là số user và active là số user đang hoạt động.", "dashboardSummary([{active:true}, {active:false}]).active => 1", ["Kết quả là object mới.", "total là users.length.", "active cần đếm bằng vòng lặp."], [{ expression: "dashboardSummary([{ active: true }, { active: false }, { active: true }]).total", expected: 3 }, { expression: "dashboardSummary([{ active: true }, { active: false }, { active: true }]).active", expected: 2 }, { expression: "dashboardSummary([]).total", expected: 0 }], "function dashboardSummary(users) {\n  let active = 0;\n  for (let user of users) {\n    if (user.active) active++;\n  }\n  return {\n    total: users.length,\n    active: active,\n  };\n}"],
  ];

  function fromTuple(tuple, group) {
    const [id, title, context, request, result, example, hint, tests, solution] = tuple;
    return { id, group, title, context, request, result, example, hint, tests, solution };
  }

  const allSpecs = specs
    .concat(loopSpecs.map((item) => fromTuple(item, "Loop")))
    .concat(functionSpecs.map((item) => fromTuple(item, "Function")))
    .concat(arraySpecs.map((item) => fromTuple(item, "Array")))
    .concat(objectSpecs.map((item) => fromTuple(item, "Object")));

  function toExercise(spec, index) {
    return {
      id: spec.id,
      level: spec.group,
      title: spec.title,
      type: spec.group,
      prompt: `Bối cảnh: ${spec.context}\nYêu cầu: ${spec.request}\nKết quả: ${spec.result}`,
      example: `Kết quả mong muốn:\n${spec.example}`,
      hint: `Gợi ý:\n- ${spec.hint.join("\n- ")}`,
      tests: spec.tests,
    };
  }

  window.basicCurriculumExercises = allSpecs.map(toExercise);
  window.basicCurriculumSolutions = Object.fromEntries(
    allSpecs.map((spec) => [spec.id, spec.solution])
  );
})();
